sudo: required
language: scala
scala:
- 2.12.6
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/"
services:
- redis-server
jobs:
  include:
  - stage: test
    script:
    - sbt "^^ 1.1.4" clean update test
    jdk: oraclejdk8
