sudo: required
language: scala
matrix:
  include:
  - env: SBT_VERSION="1.1.4"
    jdk: oraclejdk8
scala:
  - 2.12.6
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/"
services:
  - redis-server
script:
  - sbt "^^ ${SBT_VERSION}" test
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
