sudo: required
language: scala
scala:
- 2.12.6
cache:
  directories:
  - "$HOME/.ivy2/"
  - "$HOME/.sbt/"
services:
- redis-server
jobs:
  include:
  - stage: test
    script:
    - sbt "^^ 1.1.4" clean update test
    jdk: oraclejdk8
  - stage: deploy
    script: skip
    jdk: oraclejdk8
    deploy:
      provider: script
      script:
      - git checkout master
      - sbt "^^ 1.1.4" release "with-defaults"
      on:
        branch: master
        repo: d2a4u/redis-pure

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
  - secure: p89d+qYBJ8RlXmgluICVKwjiZshMOiWkRyO4c4niMEd4qTe6WuwqPw+e+h7afVzyNbjMlefsgxTnXV+Q3L0TM3SwiedH5AsoJhsaKjd0iVYK/NObkKHhHejFdYngA2O4fsDtNjOpK2BOMVg6aIj9sZmVnr1X4nrpRhj+xSyUCxffShacpms3k48nkaJDsWK3G7F3r+FW5klx6OqfP0wNqGY+yTm+1qKNME8R5vDL0C/hEl4ew1Umlvllt8FsSY9JBquGCgJtSiEqkt6/+U1egvPt0yPr4FgkXMaQBhMi0bm74X7gmK53zlA8McLIn5aR0Uf7nHpzs+jcmcyhTGwpGNgLR4MTXN57joiMg7h6AS468odYgtWvGvz93bNUx96vW2FI3d9NxSfOeR01PqkRFgegFkAjRDkqMcF7qovpO5GgHuSrkEBC4hfnGVkPAgkIUeUpMSF1PHJ2Gj2QTx5Rds+0NsYjgmTYL2uEMy5HaFEm1GLJZLLl2DJdNtLgInm6IypoQ4y1lcjshsdXPSHPurC9huAJsahHvCNuQ/EugiGj20tXiErf6jKYELPWEJhQ8MekDC1TCj8YrCgeFLMUwMqiYVqOQyxt9JBhJyhzbXg96AAjm7Fvj8u+gfABuMt/8qPOYkqYXlesd1RhSl+/CqfbcSOiDzfSdItkgn14dmY=
  - secure: apt8wSBzNzO5pJnKjW8MqDVNlNaLA7Bt2LLClcwn49NsQ40/RAqSMVJGmSW5eOElL1GzCcvgvxzQudY+GnnwJ0Ca1Fz/L9I5DXcN/T61+GjsGb7IpLG6l8IRmXYcRKMvrGChxcG608HaIbjkUeUNU8qrkq1QOYID39yMlzatdkcGFaATUCL+JkeGN3tKED1Xe1cUiTpDSo6yNFRUjlT4zzkxrlNEW7tKZPgbvsoZs9UOvYStRlQX0d7m+i2P1y9/J5DvIQUk1kN4f8a82UrVTAsPmaHnrESHiLS4Jn5QUg3bEkNiWoc0ZOJuGJUkUMq+BfHx6P6IaRdztdU4Xl+9UmPgYfdwvvxBOsW65/Hlm4boW28S3BDJgAwQjBuIQjaGMM7MUX3ltmSaJtVXMm1eiAx9FGy7ThN1XixC4umEu5cSBEe0zPSFB3r1v06C63xfdqh6/T7Yu2pl3amAu01Ltrnw3p0dn3k1qrOGDjeOkxqQeg9iu8Xz9hRatxj2H55Umbdd27aERPH4PMdr0iUY12wB4Y/0g5RYWxp9xiape7dD3MqjneqZNvFVjo7hA7Gxy+BMAK0hfuWqUx1hDK6Wwe6DS9iUBaMtmq/PViYkX+pv2dCqCe79sjOnOL7EnUW1D/jQPZMaIXJhSRvjvm6zD8jJ0cENhBRxfmj3B/YBMYg=
